"""add_delivered_at_dismissed_at_to_chapters

Revision ID: 40e95b1af33d
Revises: c7e1a2b3d4f5
Create Date: 2026-05-03 11:22:34.124213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40e95b1af33d'
down_revision: Union[str, Sequence[str], None] = 'c7e1a2b3d4f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapters', sa.Column('delivered_at', sa.DateTime(), nullable=True))
    op.add_column('chapters', sa.Column('dismissed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chapters', 'dismissed_at')
    op.drop_column('chapters', 'delivered_at')
    # ### end Alembic commands ###
